import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const WIKI_DIR = path.resolve(__dirname, '../../story-wiki');
const OUTPUT   = path.resolve(__dirname, '../src/data/wiki-generated.ts');

// Category directories map to PageCategory type
const CATEGORY_MAP: Record<string, string> = {
  stories:    'story',
  characters: 'character',
  themes:     'theme',
  techniques: 'technique',
  world:      'world',
  analyses:   'analysis',
};

function slugify(filename: string): string {
  return filename
    .replace(/\.md$/i, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

function titleFromFilename(filename: string): string {
  return filename.replace(/\.md$/i, '');
}

interface Entry {
  slug: string;
  title: string;
  category: string;
  links: string[];
  content: string;
}

const pages: Entry[] = [];

for (const [dir, category] of Object.entries(CATEGORY_MAP)) {
  const dirPath = path.join(WIKI_DIR, dir);
  if (!fs.existsSync(dirPath)) continue;

  for (const file of fs.readdirSync(dirPath)) {
    if (!file.endsWith('.md')) continue;

    const raw = fs.readFileSync(path.join(dirPath, file), 'utf-8');

    // Strip Jekyll front matter (--- ... ---)
    const content = raw.replace(/^---[\s\S]*?---\n?/, '').trim();

    // Extract [[wikilinks]] targets as slug links
    const wikiLinkPattern = /\[\[([^\]|]+)(?:\|[^\]]+)?\]\]/g;
    const links = new Set<string>();
    let m: RegExpExecArray | null;
    while ((m = wikiLinkPattern.exec(content)) !== null) {
      links.add(slugify(m[1]));
    }

    pages.push({
      slug: slugify(file),
      title: titleFromFilename(file),
      category,
      links: [...links],
      content,
    });
  }
}

const ts = `// AUTO-GENERATED by scripts/generate-wiki.ts — DO NOT EDIT MANUALLY
// Re-run: node --loader ts-node/esm scripts/generate-wiki.ts

import type { PageCategory, WikiPage } from './wiki-types';

export const wikiPages: WikiPage[] = ${JSON.stringify(pages, null, 2)
  .replace(/"category":/g, 'category:')
  .replace(/"slug":/g, 'slug:')
  .replace(/"title":/g, 'title:')
  .replace(/"links":/g, 'links:')
  .replace(/"content":/g, 'content:')};

export const pagesBySlug = new Map(wikiPages.map(p => [p.slug, p]));
export const pagesByCategory = wikiPages.reduce<Record<PageCategory, WikiPage[]>>((acc, page) => {
  if (!acc[page.category]) acc[page.category] = [];
  acc[page.category].push(page);
  return acc;
}, {} as Record<PageCategory, WikiPage[]>);
`;

fs.writeFileSync(OUTPUT, ts);
console.log(`✅ Generated ${pages.length} wiki pages → ${OUTPUT}`);
